# Generated by Django 5.1.1 on 2024-09-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_id', models.IntegerField(max_length=3)),
                ('Item_name', models.CharField(max_length=50)),
                ('Item_description', models.TextField(max_length=250)),
                ('Item_price', models.IntegerField(max_length=40)),
                ('Item_created_at', models.DateField(max_length=100)),
            ],
        ),
    ]
