# Generated by Django 5.1.1 on 2024-09-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_alter_item_item_id_alter_item_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Item_id',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='item',
            name='Item_price',
            field=models.CharField(max_length=50),
        ),
    ]
