# Generated by Django 5.1.1 on 2024-09-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0003_alter_item_item_id_alter_item_item_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Item_description',
            new_name='It_description',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Item_name',
            new_name='It_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Item_price',
            new_name='It_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Item_created_at',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Item_id',
        ),
        migrations.AddField(
            model_name='item',
            name='It_created_at',
            field=models.DateTimeField(auto_now_add=True, default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='It_id',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
