# Generated by Django 5.1.1 on 2024-09-26 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0004_rename_item_description_item_it_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='It_created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
