# Generated by Django 5.1.1 on 2024-09-26 05:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0005_alter_item_it_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='It_created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 26, 5, 8, 52, 122816, tzinfo=datetime.timezone.utc)),
        ),
    ]
