# Generated by Django 5.1.1 on 2024-09-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0006_alter_item_it_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='It_created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
