# Generated by Django 5.1.1 on 2024-09-26 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0007_alter_item_it_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='It_created_at',
        ),
    ]
