# Generated by Django 5.1.1 on 2024-09-26 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0009_item_it_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
